{{- if .Values.hooks.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "python-app.fullname" . }}-post-install"
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "{{ .Values.hooks.postInstall.weight }}"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "python-app.fullname" . }}-post-install"
      labels:
        {{- include "python-app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          imagePullPolicy: {{ .Values.hooks.image.pullPolicy }}
          command:
            {{- toYaml .Values.hooks.postInstall.command | nindent 12 }}
{{- end }}
