apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-app.fullname" . }}-config
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
data:
  config.json: |-
{{ tpl (.Files.Get "files/config.json") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-app.fullname" . }}-env
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
