{{- if eq .Values.workload.type "statefulset" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.headlessServiceName" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "python-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
