{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-app.secretName" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.data.username | quote }}
  password: {{ .Values.secrets.data.password | quote }}
{{- end }}
